// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe-5_LcxvWMzvcAUaGfv3UCMJZNAB78QM',
    appId: '1:394512063889:web:7193e512e026fce592ce30',
    messagingSenderId: '394512063889',
    projectId: 'task-manament-era',
    authDomain: 'task-manament-era.firebaseapp.com',
    storageBucket: 'task-manament-era.firebasestorage.app',
    measurementId: 'G-ZKT8W33G30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjFs12TAPHlqUvZWqpF25bM1_TOTz2HBg',
    appId: '1:394512063889:android:0189904c2227366292ce30',
    messagingSenderId: '394512063889',
    projectId: 'task-manament-era',
    storageBucket: 'task-manament-era.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAegOUEWYbh3DBdTUbt9XzE9w6i92E_NHw',
    appId: '1:394512063889:ios:f9b85f09046b188292ce30',
    messagingSenderId: '394512063889',
    projectId: 'task-manament-era',
    storageBucket: 'task-manament-era.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAegOUEWYbh3DBdTUbt9XzE9w6i92E_NHw',
    appId: '1:394512063889:ios:f9b85f09046b188292ce30',
    messagingSenderId: '394512063889',
    projectId: 'task-manament-era',
    storageBucket: 'task-manament-era.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe-5_LcxvWMzvcAUaGfv3UCMJZNAB78QM',
    appId: '1:394512063889:web:54c57e7a2f54102c92ce30',
    messagingSenderId: '394512063889',
    projectId: 'task-manament-era',
    authDomain: 'task-manament-era.firebaseapp.com',
    storageBucket: 'task-manament-era.firebasestorage.app',
    measurementId: 'G-LHCDM73FDV',
  );
}
